#!/bin/bash

# 
mvn -T 1.5C clean install -Dmaven.test.skip=true
cd target/
mvn install:install-file -Dfile=opensyd-aws-3.0.0.jar -DgroupId=com.venosyd.open -DartifactId=opensyd-aws -Dversion=3.0.0 -Dpackaging=jar
